apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-devops-chart
  labels:
    app: devops-upp
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: devops-upp
  template:
    metadata:
      labels:
        app: devops-upp
    spec:
      containers:
        - name: devops-upp
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 5000

          env:
            - name: ENV
              value: "{{ .Values.env.name }}"

          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
