apiVersion: v1
kind: Service
metadata:
  name: {{ include "devops-chart.fullname" . }}
  labels:
    {{- include "devops-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
      protocol: TCP
      name: http
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "devops-chart.selectorLabels" . | nindent 4 }}
